Create bitsearch.py
still in development, it returns sources but when passed to the sort keys it returns an error of unhashable list 
ive fixed this error several times but im not sure where its producing in this scraper. and whenever i add anything to the sort keys i get the same error, its probably an easy fix im just currently working on many other tasks so anyone that wants to heres a good start.
i provide the relevant code to look at if anything needs to be updated let me know.
 File "C:\Users\mrbla\Desktop\Kodi666\portable_data\addons\plugin.video.asguard\default.py", line 1374, in get_sources
   hosters.sort(key=utils2.get_sort_key)
 File "C:\Users\mrbla\Desktop\Kodi666\portable_data\addons\plugin.video.asguard\asguard_lib\utils2.py", line 316, in get_sort_key
if value in SORT_KEYS[field]:
TypeError: unhashable type: 'list'